/**
 * Complete Hyperlocal Kirana & Retail 44-Category Catalog Metadata
 * Matches Shopsilo Native Mobile OS catalog & search system
 */

export const ALL_CATEGORIES = [
  {
    id: 'automotive',
    slug: 'automotive',
    nameEn: 'Automotive',
    nameHi: 'गाड़ी व ऑटोमोबाइल',
    descriptionEn: 'Vehicle care, accessories and essentials',
    descriptionHi: 'गाड़ी की सफाई, एक्सेसरीज़ व जरूरी सामान',
    icon: '🚗',
    color: '#64748b',
    keywords: ['car', 'bike', 'motorcycle', 'engine oil', 'vehicle', 'tyre', 'polish', 'automotive'],
  },
  {
    id: 'baby-care',
    slug: 'baby-care',
    nameEn: 'Baby Care',
    nameHi: 'शिशु देखभाल (Baby Care)',
    descriptionEn: 'Diapers, baby food and baby essentials',
    descriptionHi: 'डायपर, बेबी सोप, वाइप्स व बेबी फूड',
    icon: '👶',
    color: '#ec4899',
    keywords: ['baby', 'diaper', 'pampers', 'huggies', 'wipes', 'cerelac', 'johnson', 'baby food'],
  },
  {
    id: 'biscuits-cookies',
    slug: 'biscuits-cookies',
    nameEn: 'Biscuits & Cookies',
    nameHi: 'बिस्कुट व कुकीज',
    descriptionEn: 'Biscuits, cookies and rusks',
    descriptionHi: 'पारले-जी, मैरी, गुड डे, ओरियो व रस्क',
    icon: '🍪',
    color: '#d97706',
    keywords: ['biscuit', 'cookie', 'rusk', 'parle', 'good day', 'oreo', 'marie', 'bourbon', 'cookies'],
  },
  {
    id: 'books-magazines',
    slug: 'books-magazines',
    nameEn: 'Books & Magazines',
    nameHi: 'किताबें व पत्रिकाएं',
    descriptionEn: 'Books, newspapers and magazines',
    descriptionHi: 'स्कूल बुक्स, नॉवेल्स व मैगजीन',
    icon: '📚',
    color: '#4f46e5',
    keywords: ['book', 'magazine', 'novel', 'newspaper', 'guide', 'dictionary'],
  },
  {
    id: 'bread-bakery',
    slug: 'bread-bakery',
    nameEn: 'Bread & Bakery',
    nameHi: 'ब्रेड, पाव व बेकरी',
    descriptionEn: 'Bread, buns, cakes and bakery products',
    descriptionHi: 'व्हाइट ब्रेड, ब्राउन ब्रेड, पाव, केक व मफिन्स',
    icon: '🍞',
    color: '#b45309',
    keywords: ['bread', 'bun', 'pav', 'cake', 'bakery', 'rusk', 'toast', 'croissant'],
  },
  {
    id: 'butter-cheese',
    slug: 'butter-cheese',
    nameEn: 'Butter & Cheese',
    nameHi: 'मक्खन, पनीर व चीज',
    descriptionEn: 'Butter, cheese, paneer and spreads',
    descriptionHi: 'अमूल बटर, चीज स्लाइस, फ्रेश पनीर व मेयोनीज',
    icon: '🧈',
    color: '#eab308',
    keywords: ['butter', 'cheese', 'paneer', 'amul', 'spread', 'mayo', 'mayonnaise', 'slice'],
  },
  {
    id: 'chips-namkeen',
    slug: 'chips-namkeen',
    nameEn: 'Chips & Namkeen',
    nameHi: 'चिप्स, नमकीन व भुजिया',
    descriptionEn: 'Chips, namkeen and savoury snacks',
    descriptionHi: 'लेज, कुरकुरे, हल्दीराम भुजिया व नमकीन मिक्सचर',
    icon: '🥨',
    color: '#f97316',
    keywords: ['chips', 'namkeen', 'lays', 'kurkure', 'bhujia', 'haldiram', 'sev', 'mixture', 'snacks'],
  },
  {
    id: 'edible-oils',
    slug: 'edible-oils',
    nameEn: 'Edible Oils',
    nameHi: 'खाद्य तेल व रिफाइंड',
    descriptionEn: 'Cooking oils, ghee and vanaspati',
    descriptionHi: 'सरसों तेल, रिफाइंड तेल, देसी घी व वनस्पति',
    icon: '🫒',
    color: '#16a34a',
    keywords: ['oil', 'mustard oil', 'refined oil', 'fortune', 'dhara', 'ghee', 'tel', 'sarson'],
  },
  {
    id: 'eggs',
    slug: 'eggs',
    nameEn: 'Eggs',
    nameHi: 'अंडे (Farm Eggs)',
    descriptionEn: 'Eggs and egg-based products',
    descriptionHi: 'फार्म फ्रेश अंडे, देसी अंडे व एग ट्रे',
    icon: '🥚',
    color: '#ca8a04',
    keywords: ['egg', 'anda', 'eggs', 'farm egg', 'desi anda', 'tray'],
  },
  {
    id: 'electronics',
    slug: 'electronics',
    nameEn: 'Electronics',
    nameHi: 'इलेक्ट्रॉनिक सामान व गैजेट्स',
    descriptionEn: 'Small appliances and consumer electronics',
    descriptionHi: 'स्मार्टवॉच, ब्लूटूथ स्पीकर, ट्रिमर व गैजेट्स',
    icon: '⚡',
    color: '#f59e0b',
    keywords: ['electronics', 'speaker', 'bluetooth', 'trimmer', 'smartwatch', 'torch', 'iron', 'kettle'],
  },
  {
    id: 'flour-atta',
    slug: 'flour-atta',
    nameEn: 'Flour & Atta',
    nameHi: 'आटा, मैदा व बेसन',
    descriptionEn: 'Atta, maida, besan and baking flour',
    descriptionHi: 'आशीर्वाद चक्की आटा, मैदा, सूजी व चना बेसन',
    icon: '🌾',
    color: '#eab308',
    keywords: ['atta', 'flour', 'aashirvaad', 'maida', 'besan', 'sooji', 'suji', 'wheat', 'gehu'],
  },
  {
    id: 'footwear',
    slug: 'footwear',
    nameEn: 'Footwear',
    nameHi: 'जूते, चप्पल व सैंडल',
    descriptionEn: 'Shoes, sandals and slippers',
    descriptionHi: 'हवाई चप्पल, फॉर्मल जूते, स्नीकर्स व सैंडल',
    icon: '👟',
    color: '#6366f1',
    keywords: ['shoes', 'chappal', 'slipper', 'sandals', 'footwear', 'bata', 'relaxo', 'sparx'],
  },
  {
    id: 'fresh-fruits',
    slug: 'fresh-fruits',
    nameEn: 'Fresh Fruits',
    nameHi: 'ताजे फल (Fresh Fruits)',
    descriptionEn: 'Fresh seasonal fruits',
    descriptionHi: 'सेब, केला, अनार, संतरा व मौसमी फल',
    icon: '🍎',
    color: '#ef4444',
    keywords: ['fruits', 'apple', 'banana', 'orange', 'mango', 'pomegranate', 'seb', 'kela', 'fal'],
  },
  {
    id: 'fresh-vegetables',
    slug: 'fresh-vegetables',
    nameEn: 'Fresh Vegetables',
    nameHi: 'ताजी सब्जियां (Vegetables)',
    descriptionEn: 'Fresh vegetables and leafy greens',
    descriptionHi: 'आलू, प्याज, टमाटर, हरी मिर्च व ताजी हरी सब्जियां',
    icon: '🥦',
    color: '#16a34a',
    keywords: ['vegetables', 'potato', 'onion', 'tomato', 'aloo', 'pyaz', 'tamatar', 'sabzi', 'gobhi'],
  },
  {
    id: 'general-store',
    slug: 'general-store',
    nameEn: 'General Store',
    nameHi: 'जनरल स्टोर व विविध',
    descriptionEn: 'Stationery, plastics, gifts and miscellaneous items',
    descriptionHi: 'प्लास्टिक बाल्टी, मग, हैंगर व रोजमर्रा का सामान',
    icon: '🏪',
    color: '#0284c7',
    keywords: ['general', 'plastic', 'bucket', 'mug', 'hanger', 'container', 'miscellaneous'],
  },
  {
    id: 'gifts-handicrafts',
    slug: 'gifts-handicrafts',
    nameEn: 'Gifts & Handicrafts',
    nameHi: 'उपहार व हैंडीक्राफ्ट',
    descriptionEn: 'Gifts, decor and handmade products',
    descriptionHi: 'गिफ्ट पैक, डेकोरेशन आइटम व फोटो फ्रेम',
    icon: '🎁',
    color: '#db2777',
    keywords: ['gift', 'toys', 'handicraft', 'decor', 'photo frame', 'present', 'showpiece'],
  },
  {
    id: 'hair-care',
    slug: 'hair-care',
    nameEn: 'Hair Care',
    nameHi: 'हेयर केयर व शैम्पू',
    descriptionEn: 'Shampoo, conditioner, oil and hair styling',
    descriptionHi: 'हेड एंड शोल्डर्स, क्लिनिक प्लस, डाबर आंवला व तेल',
    icon: '🧴',
    color: '#06b6d4',
    keywords: ['hair', 'shampoo', 'conditioner', 'oil', 'dabur amla', 'clinic plus', 'parachute', 'serum'],
  },
  {
    id: 'hardware-electrical',
    slug: 'hardware-electrical',
    nameEn: 'Hardware & Electrical',
    nameHi: 'इलेक्ट्रिकल, बल्ब व टूल्स',
    descriptionEn: 'Tools, bulbs, wires and electrical supplies',
    descriptionHi: 'LED बल्ब, स्विच, टेप, पेचकस व हथौड़ी',
    icon: '💡',
    color: '#ca8a04',
    keywords: ['bulb', 'led bulb', 'switch', 'wire', 'tape', 'hardware', 'screw', 'tools', 'electric'],
  },
  {
    id: 'home-cleaning',
    slug: 'home-cleaning',
    nameEn: 'Home Cleaning',
    nameHi: 'घर की सफाई व फिनाइल',
    descriptionEn: 'Floor, toilet, dish and surface cleaners',
    descriptionHi: 'हार्पिक, लाइजोल, विम बार, फिनाइल व डिशवॉश',
    icon: '🧽',
    color: '#14b8a6',
    keywords: ['cleaning', 'harpic', 'lizol', 'phenyl', 'vim', 'dishwash', 'cleaner', 'mortein', 'all out'],
  },
  {
    id: 'kids-clothing',
    slug: 'kids-clothing',
    nameEn: 'Kids Clothing',
    nameHi: 'बच्चों के कपड़े (Kids Wear)',
    descriptionEn: 'Kids clothing and school wear',
    descriptionHi: 'बच्चों के फ्रॉक, टी-शर्ट, निकर व स्कूल ड्रेस',
    icon: '👕',
    color: '#38bdf8',
    keywords: ['kids', 'bache', 'school uniform', 'frock', 'tshirt', 'baby clothes'],
  },
  {
    id: 'kitchen-supplies',
    slug: 'kitchen-supplies',
    nameEn: 'Kitchen Supplies',
    nameHi: 'रसोई बर्तन व डिब्बे',
    descriptionEn: 'Kitchen tools, containers and consumables',
    descriptionHi: 'मसाला डिब्बे, स्टील बर्तन, चाकू व एल्युमिनियम फॉयल',
    icon: '🍳',
    color: '#f59e0b',
    keywords: ['kitchen', 'foil', 'container', 'knife', 'bartan', 'spoons', 'glass', 'tiffin'],
  },
  {
    id: 'laundry-care',
    slug: 'laundry-care',
    nameEn: 'Laundry Care',
    nameHi: 'सर्फ, डिटर्जेंट व कपड़े धुलाई',
    descriptionEn: 'Detergent, fabric care and stain removers',
    descriptionHi: 'सर्फ एक्सेल, टाइड, घड़ी डिटर्जेंट, रिन साबुन व उजाला',
    icon: '🧺',
    color: '#3b82f6',
    keywords: ['surf', 'detergent', 'surf excel', 'tide', 'ghadi', 'rin', 'ujala', 'washing powder'],
  },
  {
    id: 'meat-seafood',
    slug: 'meat-seafood',
    nameEn: 'Meat & Seafood',
    nameHi: 'चिकन, मटन व मछली',
    descriptionEn: 'Meat, chicken, fish and seafood',
    descriptionHi: 'ताजा चिकन, मटन, रोहू मछली व प्रॉन्स',
    icon: '🍗',
    color: '#dc2626',
    keywords: ['meat', 'chicken', 'mutton', 'fish', 'seafood', 'prawns', 'machli', 'gosht'],
  },
  {
    id: 'mens-clothing',
    slug: 'mens-clothing',
    nameEn: 'Mens Clothing',
    nameHi: 'मेंस वियर व होजरी',
    descriptionEn: 'Mens clothing and daily wear',
    descriptionHi: 'टी-शर्ट, शर्ट, जींस, लोअर, गंजी व अंडरवियर',
    icon: '👕',
    color: '#0284c7',
    keywords: ['mens', 'tshirt', 'shirt', 'jeans', 'lower', 'underwear', 'vest', 'gamchha'],
  },
  {
    id: 'milk-curd',
    slug: 'milk-curd',
    nameEn: 'Milk & Curd',
    nameHi: 'दूध, दही व छाछ',
    descriptionEn: 'Milk, curd and dairy beverages',
    descriptionHi: 'अमूल दूध, ताजा दही, छाछ, लस्सी व खोया',
    icon: '🥛',
    color: '#38bdf8',
    keywords: ['milk', 'doodh', 'curd', 'dahi', 'chaas', 'lassi', 'amul', 'mother dairy'],
  },
  {
    id: 'mobile-accessories',
    slug: 'mobile-accessories',
    nameEn: 'Mobile Accessories',
    nameHi: 'मोबाइल चार्जर व केबल्स',
    descriptionEn: 'Chargers, cables, cases and earphones',
    descriptionHi: 'फास्ट चार्जर, टाइप-सी केबल, इयरफोन व बैक कवर',
    icon: '🔌',
    color: '#f59e0b',
    keywords: ['mobile', 'charger', 'cable', 'type c', 'earphone', 'cover', 'glass', 'power bank'],
  },
  {
    id: 'oral-care',
    slug: 'oral-care',
    nameEn: 'Oral Care',
    nameHi: 'टूथपेस्ट व ब्रश',
    descriptionEn: 'Toothpaste, brushes and mouth care',
    descriptionHi: 'कोलगेट, क्लोजअप, सेंसोडाइन, टूथब्रश व माउथवॉश',
    icon: '🪥',
    color: '#06b6d4',
    keywords: ['toothpaste', 'toothbrush', 'colgate', 'closeup', 'sensodyne', 'dabur red', 'oral b'],
  },
  {
    id: 'packaged-foods',
    slug: 'packaged-foods',
    nameEn: 'Packaged Foods',
    nameHi: 'पैकेज्ड फूड व रेडी-टू-ईट',
    descriptionEn: 'Ready-to-cook, canned and packaged foods',
    descriptionHi: 'मैगी नूडल्स, पास्ता, सूप, जैम व केचप',
    icon: '🥫',
    color: '#ea580c',
    keywords: ['maggi', 'noodles', 'pasta', 'soup', 'ketchup', 'jam', 'sauce', 'ready to cook'],
  },
  {
    id: 'pet-supplies',
    slug: 'pet-supplies',
    nameEn: 'Pet Supplies',
    nameHi: 'पेट फूड व डॉग फूड',
    descriptionEn: 'Pet food, hygiene and accessories',
    descriptionHi: 'पेडिग्री डॉग फूड, कैट फूड व पेट शैम्पू',
    icon: '🐕',
    color: '#b45309',
    keywords: ['pet', 'dog food', 'pedigree', 'cat food', 'whiskas', 'pet care'],
  },
  {
    id: 'pharmacy',
    slug: 'pharmacy',
    nameEn: 'Pharmacy',
    nameHi: 'दवाएं व फर्स्ट एड',
    descriptionEn: 'Daily medicines and first-aid products',
    descriptionHi: 'दर्द निवारक बाम, विक्स, बैंड-एड, डेटॉल व ओआरएस',
    icon: '💊',
    color: '#e11d48',
    keywords: ['pharmacy', 'medicine', 'balm', 'zandu balm', 'moov', 'vicks', 'bandaid', 'dawa'],
  },
  {
    id: 'puja-religious',
    slug: 'puja-religious',
    nameEn: 'Puja & Religious',
    nameHi: 'पूजा सामग्री व अगरबत्ती',
    descriptionEn: 'Puja items, incense and religious essentials',
    descriptionHi: 'अगरबत्ती, कपूर, रोली, चंदन, दीया तेल व बाती',
    icon: '🪔',
    color: '#f59e0b',
    keywords: ['puja', 'agarbatti', 'dhoop', 'kapoor', 'diya', 'chandan', 'machis', 'gangajal'],
  },
  {
    id: 'pulses-lentils',
    slug: 'pulses-lentils',
    nameEn: 'Pulses & Lentils',
    nameHi: 'दालें, चना व राजमा',
    descriptionEn: 'Dal, rajma, chana, peas and lentils',
    descriptionHi: 'अरहर दाल, मूंग दाल, चना दाल, मसूर, राजमा व छोले',
    icon: '🥣',
    color: '#d97706',
    keywords: ['dal', 'pulses', 'lentils', 'chana', 'rajma', 'arhar', 'moong', 'chhole', 'urad'],
  },
  {
    id: 'rice-grains',
    slug: 'rice-grains',
    nameEn: 'Rice & Grains',
    nameHi: 'चावल, बासमती व अनाज',
    descriptionEn: 'Rice, wheat, millets, oats and other grains',
    descriptionHi: 'बासमती चावल, कोलम, मंसूरी चावल, पोहा व ओट्स',
    icon: '🍚',
    color: '#0284c7',
    keywords: ['rice', 'chawal', 'basmati', 'kolam', 'poha', 'oats', 'grains', 'dalia'],
  },
  {
    id: 'skin-care',
    slug: 'skin-care',
    nameEn: 'Skin Care',
    nameHi: 'स्किन केयर व क्रीम',
    descriptionEn: 'Creams, lotions, face care and sunscreen',
    descriptionHi: 'फेयर एंड लवली, पोंड्स, निविया लोशन व बोरोलीन',
    icon: '🧴',
    color: '#ec4899',
    keywords: ['cream', 'lotion', 'ponds', 'nivea', 'vaseline', 'fair lovely', 'boroline', 'facewash'],
  },
  {
    id: 'soap-bath',
    slug: 'soap-bath',
    nameEn: 'Soap & Bath',
    nameHi: 'नहाने का साबुन व बॉडी वॉश',
    descriptionEn: 'Bath soaps, body wash and bath essentials',
    descriptionHi: 'डेटॉल, लक्स, लाइफबॉय, डव, पियर्स व संतूर साबुन',
    icon: '🧼',
    color: '#f43f5e',
    keywords: ['soap', 'dettol', 'lux', 'lifebuoy', 'dove', 'santoor', 'pears', 'body wash', 'bath'],
  },
  {
    id: 'soft-drinks-juices',
    slug: 'soft-drinks-juices',
    nameEn: 'Soft Drinks & Juices',
    nameHi: 'कोल्ड ड्रिंक्स व जूस',
    descriptionEn: 'Cold drinks, juices, water and energy drinks',
    descriptionHi: 'कोका-कोला, थम्स अप, फ्रूटी, रियल जूस व मिनरल वाटर',
    icon: '🥤',
    color: '#06b6d4',
    keywords: ['coke', 'pepsi', 'frooti', 'thums up', 'juice', 'real juice', 'sprite', 'water', 'red bull'],
  },
  {
    id: 'spices-masala',
    slug: 'spices-masala',
    nameEn: 'Spices & Masala',
    nameHi: 'मसाले व खड़ा मसाला',
    descriptionEn: 'Whole spices, powders and masala blends',
    descriptionHi: 'एमडीएच, एवरेस्ट हल्दी, मिर्च पाउडर, धनिया व गरम मसाला',
    icon: '🌶️',
    color: '#dc2626',
    keywords: ['masala', 'spices', 'haldi', 'mirch', 'dhaniya', 'jeera', 'everest', 'mdh', 'garam masala'],
  },
  {
    id: 'sports-fitness',
    slug: 'sports-fitness',
    nameEn: 'Sports & Fitness',
    nameHi: 'स्पोर्ट्स व फिटनेस',
    descriptionEn: 'Sports goods and fitness accessories',
    descriptionHi: 'क्रिकेट बैट, गेंद, बैडमिंटन व जिम एक्सेसरीज़',
    icon: '⚽',
    color: '#16a34a',
    keywords: ['sports', 'cricket', 'bat', 'ball', 'badminton', 'shuttle', 'football', 'gym'],
  },
  {
    id: 'stationery-office',
    slug: 'stationery-office',
    nameEn: 'Stationery & Office',
    nameHi: 'पेन, कॉपी व स्टेशनरी',
    descriptionEn: 'Pens, paper, notebooks and office supplies',
    descriptionHi: 'बॉल पेन, कॉपियां, रजिस्टर, स्टेपलर व फेविकोल',
    icon: '📚',
    color: '#4f46e5',
    keywords: ['pen', 'copy', 'notebook', 'register', 'fevicol', 'tape', 'stationery', 'pencil'],
  },
  {
    id: 'sugar-salt',
    slug: 'sugar-salt',
    nameEn: 'Sugar & Salt',
    nameHi: 'चीनी, नमक व गुड़',
    descriptionEn: 'Sugar, salt, jaggery and sweeteners',
    descriptionHi: 'टाटा नमक, सफेद चीनी, देसी गुड़ व सेंधा नमक',
    icon: '🧂',
    color: '#64748b',
    keywords: ['sugar', 'cheeni', 'salt', 'namak', 'tata salt', 'jaggery', 'gud', 'rock salt'],
  },
  {
    id: 'tea-coffee',
    slug: 'tea-coffee',
    nameEn: 'Tea & Coffee',
    nameHi: 'चाय पत्ती व कॉफ़ी',
    descriptionEn: 'Tea, coffee, premixes and hot beverages',
    descriptionHi: 'टाटा टी, रेड लेबल, नेस्कैफे कॉफ़ी व बॉर्नविटा',
    icon: '☕',
    color: '#78350f',
    keywords: ['tea', 'chai', 'coffee', 'nescafe', 'tata tea', 'red label', 'bournvita', 'horlicks'],
  },
  {
    id: 'toys-games',
    slug: 'toys-games',
    nameEn: 'Toys & Games',
    nameHi: 'खिलौने व गेम्स',
    descriptionEn: 'Toys, games and children entertainment',
    descriptionHi: 'रिमोट कार, गुड़िया, लूडो, कैरम व पजल्स',
    icon: '🧸',
    color: '#f59e0b',
    keywords: ['toys', 'games', 'car', 'doll', 'ludo', 'carrom', 'puzzle', 'khilauna'],
  },
  {
    id: 'vitamins-supplements',
    slug: 'vitamins-supplements',
    nameEn: 'Vitamins & Supplements',
    nameHi: 'च्यवनप्राश व न्यूट्रिशन',
    descriptionEn: 'Vitamins, nutrition and wellness products',
    descriptionHi: 'डाबर च्यवनप्राश, ग्लूकोज पाउडर, विटामिन व इम्युनिटी बूस्टर',
    icon: '💊',
    color: '#f97316',
    keywords: ['vitamin', 'supplement', 'chyawanprash', 'glucose', 'glucon d', 'nutrition', 'protein'],
  },
  {
    id: 'womens-clothing',
    slug: 'womens-clothing',
    nameEn: 'Womens Clothing',
    nameHi: 'महिला कपड़े व कुर्ती',
    descriptionEn: 'Womens clothing and daily wear',
    descriptionHi: 'साड़ी, कुर्ती, लेगिंग्स, दुपट्टा व नाइटवियर',
    icon: '👗',
    color: '#ec4899',
    keywords: ['womens', 'saree', 'kurti', 'leggings', 'dupatta', 'suit', 'nighty', 'dress'],
  },
];

export const getCategoryMeta = (catOrId) => {
  if (!catOrId) return null;
  const idOrName = typeof catOrId === 'string' ? catOrId : (catOrId.id || catOrId.slug || catOrId.name || '');
  const lower = idOrName.toLowerCase().trim();

  // 1. Direct match
  const direct = ALL_CATEGORIES.find(
    c => c.id.toLowerCase() === lower ||
         c.slug.toLowerCase() === lower ||
         c.nameEn.toLowerCase() === lower ||
         c.nameHi === idOrName
  );
  if (direct) return direct;

  // 2. Keyword match
  for (const cat of ALL_CATEGORIES) {
    if (cat.keywords.some(k => lower.includes(k) || k.includes(lower))) {
      return cat;
    }
  }

  // 3. Fallback
  return {
    id: typeof catOrId === 'object' ? catOrId.id || catOrId.slug || 'custom' : catOrId,
    slug: typeof catOrId === 'object' ? catOrId.slug || catOrId.id || 'custom' : catOrId,
    nameEn: typeof catOrId === 'object' ? catOrId.name || catOrId.id : catOrId,
    nameHi: typeof catOrId === 'object' ? catOrId.name || catOrId.id : catOrId,
    descriptionEn: 'Neighborhood store category',
    descriptionHi: 'स्थानीय दुकान की श्रेणी',
    icon: '🏷️',
    color: '#6366f1',
    keywords: [],
  };
};
